format = "$directory$git_branch$git_status$fill$lua$python$nodejs$kubernetes$aws$docker_context$golang$terraform$jobs$cmd_duration$line_break$character\n"
palette = "temp"
[directory]
format = "[$path ]($style)"
style = "bold fg:matte_blue"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = ".../"

[directory.substitutions]

[fill]
symbol = " "

[git_branch]
format = "[on](tan) [$symbol$branch ]($style)"
style = "fg:matte_green"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "fg:matte_green"

[palettes.temp]
blue = "#5B94CD"
dark_blue = "#5E81AC"
gray = "#434C5E"
green = "#91CA61"
matte_blue = "#8DADCD"
matte_green = "#A3BE8C"
orange = "#D08870"
purple = "#B48EAD"
red = "#BF616A"
tan = "#F4DC9A"
teal = "#3ACDE7"
yellow = "#EBCB8B"

