[style]
border = { fg = "highlight_med" }
input = { fg = "text", bg = "base" }
cursor = { fg = "rose", bg = "highlight_med" }
selection = { fg = "text", bg = "highlight_low" }
status = { fg = "subtle", bg = "surface" }

[icon]
color = "rose"

[syntax]
comment = "muted"
constant = "iris"
string = "gold"
variable = "foam"
keyword = "rose"
function = "pine"
type = "iris"
tag = "love"
namespace = "subtle"
text = "text"

[color]
base = "#191724"
surface = "#1f1d2e"
overlay = "#26233a"
muted = "#6e6a86"
subtle = "#908caa"
text = "#e0def4"
love = "#eb6f92"
gold = "#f6c177"
rose = "#ebbcba"
pine = "#31748f"
foam = "#9ccfd8"
iris = "#c4a7e7"
highlight_low = "#21202e"
highlight_med = "#403d52"
highlight_high = "#524f67"
