# Starship config generated for theme: swamp

format = "$directory$git_branch$git_status$fill$lua$python$nodejs$kubernetes$aws$docker_context$golang$terraform$jobs$cmd_duration$line_break$character\n"
palette = "temp"

[directory]
format = "[$path ]($style)"
style = "bold fg:matte_blue"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = ".../"

[directory.substitutions]

[fill]
symbol = " "

[git_branch]
format = "[on](tan) [$symbol$branch ]($style)"
style = "fg:matte_green"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "fg:matte_green"

[palettes.temp]
blue = "#B496B6"
dark_blue = "#FFFEDB"
gray = "#000000"
green = "#A2A970"
matte_blue = "#B496B6"
matte_green = "#A2A970"
orange = "#6A865F"
purple = "#8BADA6"
red = "#D6D6D6"
tan = "#DEBF7C"
teal = "#6A865F"
yellow = "#8BADA6"
