# Starship config generated for theme: kanagawa-dragon

format = "$directory$git_branch$git_status$fill$lua$python$nodejs$kubernetes$aws$docker_context$golang$terraform$jobs$cmd_duration$line_break$character\n"
palette = "temp"

[directory]
format = "[$path ]($style)"
style = "bold fg:matte_blue"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = ".../"

[directory.substitutions]

[fill]
symbol = " "

[git_branch]
format = "[on](tan) [$symbol$branch ]($style)"
style = "fg:matte_green"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "fg:matte_green"

[palettes.temp]
blue = "#a292a3"
dark_blue = "#FF9E3B"
gray = "#0d0c0c"
green = "#87a987"
matte_blue = "#a292a3"
matte_green = "#87a987"
orange = "#c4b28a"
purple = "#8ea4a2"
red = "#c4746e"
tan = "#b98d7b"
teal = "#c4b28a"
yellow = "#8ea4a2"
